version = "1"

includes = ["profiles.local.toml", "profiles.local.credentials.toml"]

[global]
restic-stale-lock-age = "2h"
prevent-sleep = true
verbose = true

[default]
force-inactive-lock = true

[default.backup]
verbose = true
compression = "max"
exclude-file = "excludes.txt"
exclude-caches = true

[default.retention]
after-backup = true
verbose = true
keep-hourly = 0
keep-daily = 7
keep-weekly = 5
keep-monthly = 12
prune = true
group-by = ""
