set fish_color_autosuggestion 9C9C9C
set fish_color_command F4F4F4
set fish_color_comment B0B0B0
set fish_color_cwd green
set fish_color_cwd_root red
set fish_color_end 969696
set fish_color_error FFA779
set fish_color_escape cyan
set fish_color_history_current cyan
set fish_color_host \x2do\x1ecyan
set fish_color_match cyan
set fish_color_normal normal
set fish_color_operator cyan
set fish_color_param A0A0F0
set fish_color_quote 666A80
set fish_color_redirection FAFAFA
set fish_color_search_match \x2d\x2dbackground\x3dpurple
set fish_color_selection \x2d\x2dbackground\x3dpurple
set fish_color_status red
set fish_color_user \x2do\x1egreen
set fish_color_valid_path \x2d\x2dunderline
set fish_pager_color_completion normal
set fish_pager_color_description 555\x1eyellow
set fish_pager_color_prefix cyan
set fish_pager_color_progress cyan
