import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[font]
size = 18.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
dynamic_title = true
padding = { x = 10, y = 10 }
decorations = "none"

