#!/bin/sh
AUTHORINFO=$(git var GIT_AUTHOR_IDENT) || exit 1
NAME=$(printf '%s\n\n' "${AUTHORINFO}" | sed -n 's/^\(.*\) <.*$/\1/p')
EMAIL=$(printf '%s\n\n' "${AUTHORINFO}" | sed -n 's/^.* <\(.*\)> .*$/\1/p')

if [ "${EMAIL}" != "blomma@gmail.com" ]
then
	cat <<EOF >&2
Error: user.email not set to "blomma@gmail.com" it was <${EMAIL}>
EOF
	exit 2
fi
