"$schema" = 'https://starship.rs/config-schema.json'

# format = """
# [](#9A348E)\
# $username\
# [](bg:#DA627D fg:#9A348E)\
# $directory\
# [](fg:#DA627D bg:#FCA17D)\
# [](fg:#FCA17D bg:#86BBD8)\
# $git_branch\
# $git_status\
# [](fg:#86BBD8 bg:#06969A)\
# [](fg:#06969A bg:#33658A)\
# [ ](fg:#33658A)\
# """

format = """
[](inverted #9A348E)\
[](fg:#9A348E bg:#DA627D)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
[](fg:#FCA17D bg:#86BBD8)\
[](fg:#86BBD8 bg:#06969A)\
[](fg:#06969A bg:#33658A)\
$git_branch\
$git_status\
[ ](fg:#33658A)\
"""

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#33658A"
format = '[[ $symbol $branch ](bg:#33658A)]($style)'

[git_status]
style = "bg:#33658A"
format = '[[($all_status$ahead_behind )](bg:#33658A)]($style)'

